//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FurnitureEntities : DbContext
    {
        public FurnitureEntities()
            : base("name=FurnitureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Cart> Carts { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<DesignFurniture> DesignFurnitures { get; set; }
        public DbSet<DetailCart> DetailCarts { get; set; }
        public DbSet<DetailImportGood> DetailImportGoods { get; set; }
        public DbSet<DetailOrder> DetailOrders { get; set; }
        public DbSet<DisCount> DisCounts { get; set; }
        public DbSet<Good> Goods { get; set; }
        public DbSet<ImportGood> ImportGoods { get; set; }
        public DbSet<ListRequest> ListRequests { get; set; }
        public DbSet<ListTypeGood> ListTypeGoods { get; set; }
        public DbSet<SubImgDesign> SubImgDesigns { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TableComment> TableComments { get; set; }
        public DbSet<TypeGood> TypeGoods { get; set; }
        public DbSet<SubImage> SubImages { get; set; }
    }
}
