//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListTypeGood
    {
        public ListTypeGood()
        {
            this.Goods = new HashSet<Good>();
        }
    
        public int IdTypeG { get; set; }
        public string IdRoom { get; set; }
        public string NameTypeG { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
        public virtual TypeGood TypeGood { get; set; }
    }
}
