//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeGood
    {
        public TypeGood()
        {
            this.ListTypeGoods = new HashSet<ListTypeGood>();
        }
    
        public string IdType { get; set; }
        public string NameType { get; set; }
    
        public virtual ICollection<ListTypeGood> ListTypeGoods { get; set; }
    }
}
